---
tbl-cap-location: bottom
---


## Outbreak analytics with R - course {#pre-summit-training}

**Dates:** Monday 25 November to Friday 29 November 2024 (5 days)

**Times:** 9:30-12:30 and 14:00 - 17:00

**Location:** F1 seminar room in MRCG

### Overview:

This week-long in-person workshop provide a practical introduction to outbreak data analysis using R packages developed by the Epiverse-TRACE initiative..

Fill out this [form to apply](https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&token=09a01e121b9447dbbec65057eece25af&id=oaKtcild7U6xlPh0V3cUnuJi79dolFdJoZ1qVAcSQu9UMVNUTzdEWk9CNTJMNFZNQlM2UlQ4UDNHVi4u) for this training. Application deadline is **Friday 27th September**. Places are limited and will be given on a first come, first served basis. There is no registration fee and limited funds are available for travel and local expenses. Application data will be kept confidential and may only be published in aggregated and anonymised forms in Epiverse-TRACE outreach reports. If you have any other questions about the training, please send an email to [andree.valle-campos\@lshtm.ac.uk]() or [lshad35\@lshtm.ac.uk]().

## Course content

### Day 1

-   Why use R packages for epidemic analytics?
-   How to import data into the R environment?
-   How to manipulate data in R?
-   How to perform visualization in R?

### Day 2

-   How do I simulate disease spread using a mathematical model?
-   How do I investigate the effect of interventions on disease trajectories?
-   How can we estimate final size of an epidemic?


### Day 3

-   How to clean and standardize case data?
-   How to aggregate and visualize case data?
-   How can I ensure the above tasks are performed in an efficient and reproducible way?

### Day 4

-   What are the delay distributions and what is their usage on outbreak analytics?
-   How to access delay distributions from a literature search database?
-   How can I estimate key transmission metrics from a time series of case data?
-   How do I account for incomplete reporting in forecasts?

### Day 5

-   How to estimate the case fatality ratio (CFR) and adjust for common biases?
-   How can we estimate individual-level variation in transmission (i.e. superspreading potential)?
-   How can we simulate transmission chains based on infection characteristics?

## Timetable

|          Date and time           | Topic                                                                              |
|:---------------------------------:|:------------------------------------|
|  Monday 25 June (9:30 - 12:30)   | A refresher on the basics of R: data input, data Subsetting, and data manipulation |
|  Monday 25 June (2:00 - 17:00)   | A refresher on the basics of R: functions, visualization, and statistics           |
|  Tuesday 26 June (9:30 - 12:30)  | Simulate disease spread|
|  Tuesday 26 June (2:00 - 17:00)  | Simulate disease tramsmission with interventions|
| Wednesday 27 June (9:30 - 12:30) | Read, clean, and standardize outbreak case data|
| Wednesday 27 June (2:00 - 17:00) | Validate, aggregate and visualize outbreak case data|
| Thursday 28 June (9:30 - 12:30)  | A primer on delay distributions and their usage in outbreak analytics              |
| Thursday 28 June (2:00 - 17:00)  | Access epidemiological parameters and estimate transmission metrics                |
|  Friday 29 June (9:30 - 12:30)   | Forecast of cases and estimate outbreak severity                                   |
|  Friday 29 June (2:00 - 17:00)   | Estimate superspreading   and simulate transmission chain |
: Course schedule {.striped .hover}


## Prerequisites

Attendees will need to work on their own laptops. We expect participants to have some exposure to basic statistical, mathematical and epidemic theory concepts, but NOT necessarily familiarity with analytics or modelling. This workshop requires you to be familiar with:

- **Data science**: Some basic familiarity with R software
- **Statistics**: Familiarity with common probability distributions, such as the Normal, Gamma, Log normal, and Negative binomial distributions.
- **Epidemic theory**: Familiarity with common epidemiological parameters, such as the incubation period, generation time, and serial interval, and metrics such as the reproduction number.
